### ISSUE TITLE
tox: dev env

### ISSUE THREAD

**Issue by mj0nez** [mj0nez/energy-datetime-utils#12]
@hf-kklein, could you help me understand the benefits of this testenv? 
I really liked the simplicity of invoking tests, linting, typing and so forth. Therefore, I’ve added the format env to orchestrate isort and black, too. But it seems that with ‘dev’ we just replicate the pip upgrade and installation of all dependencies in another tox-environment.

the dev [tox.ini](https://github.com/mj0nez/energy-datetime-utils/blob/a996ac5ad0023abc1587e5debb08ed19b2bd2203/tox.ini)
```
[testenv:dev]
# the dev environment contains everything you need to start developing on your local machine.
deps =
    {[testenv:tests]deps}
    {[testenv:linting]deps}
    {[testenv:format]deps}
    pip-tools
commands =
    python -m pip install --upgrade pip
```

**Comment by hf-kklein** [comment]
Hi, die Idee ist, dass die dev-Umgebung in der IDE verwendet wird. Dann sind alle Tools, die man so brauchen könnte, in einer einzigen "Mehrzweck-venv" verfügbar. Wenn man z.b. "nur mal eben" was formatieren möchte, muss man nicht erst in die Formatting-Env wechseln und wenn man z.B. nur für eine einzelne Datei die Linter oder Tests abfeuern möchte, muss man nicht gleich mit `tox -e linting_oder_test_env` die komplette Code-Basis prüfen (was ja auch ein paar Minuten dauern kann), sondern kann punktuell/zielgenau das prüfen, worauf gerade der eigene Fokus liegt (typischerweise kurz hintereinander tests+linter). Für eine effiziente Entwicklung wäre es hinderlich, wenn man z.B. der IDE immer wieder pytest oder den Formatter unter den Füßen wegziehen würde.

V.a. beim Refactoren ist das sehr hilfreich.

Die eine "einmal hin, alles drin"-`dev`-Umgebung ist auch hilfreich, damit Leute, die neu in einer Code-Basis sind, schnell produktiv werden können. In der Anleitung in [unserem Python-Template-Repo](https://github.com/Hochfrequenz/python_template_repository#how-to-use-this-repository-on-your-machine) sieht man, dass es mit der einen großen dev-Umgebung, die sich aus den anderen scharf abgegrenzten tox-envs zusammensetzt, nur wenige manuelle Schritte braucht, um in die Entwicklung einsteigen zu können (im Wesentlichen `tox -e dev` und dann `.tox/dev/Scrips/python` als Interpreter setzen). D.h. Entwickler*innen können sich direkt aufs Wesentliche konzentrieren, statt lange Zeit mit einem von Projekt zu Projekt unterschiedlichen Setup herum zu werkeln.

**Comment by mj0nez** [comment]
Hey, vielen Dank für die ausführliche Erklärung! Das sollte einige meiner Probleme lösen... Ich werds in meinen Workflow übernehmen. :)
